// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    title: "The Blender",
    description:
      "A tool for tracking and managing Fundación En Via microloans.",
    coverImg: "The_Blender.png",
    program1: "devicon-ruby-plain",
    program2: "devicon-rails-plain-wordmark",
    program3: "devicon-postgresql-plain",
    program4: "devicon-html5-plain",
    program5: "devicon-css3-plain",
    github: "devicon-github-original-wordmark",
  },
  {
    id: 2,
    title: "Deckfinder",
    description: "A market place for card players and card collectors",
    coverImg: "Deckfinder.png",
    program1: "devicon-ruby-plain",
    program2: "devicon-rails-plain-wordmark",
    program3: "devicon-postgresql-plain",
    program4: "devicon-html5-plain",
    program5: "devicon-css3-plain",
    github: "devicon-github-original-wordmark",
  },
  {
    id: 3,
    title: "Movie Watch List",
    description: "A web app to track and organize your favorite movies",
    coverImg: "watch_list.png",
    program1: "devicon-ruby-plain",
    program2: "devicon-rails-plain-wordmark",
    program3: "devicon-postgresql-plain",
    program4: "devicon-html5-plain",
    program5: "devicon-css3-plain",
    github: "devicon-github-original-wordmark",
  },
  {
    id: 4,
    title: "Note Keep",
    description: "A clone of google Note Keep",
    coverImg: "Keep.png",
    program1: "devicon-html5-plain",
    program2: "devicon-css3-plain",
    program3: "devicon-javascript-plain",
    program4: "devicon-react-original-wordmark",
    github: "devicon-github-original-wordmark",
  },
];
